### ISSUE TITLE
Simulator Launches but shows Blank Screen

### ISSUE THREAD

**Issue by Shorkerrr** [nameouschangey/STORMWORKS_VSCodeExtension#13] opened 2021-12-09 19:56 UTC
![bild](https://user-images.githubusercontent.com/95881003/145466551-81639c90-c8f7-4863-8f98-c550c2175c2a.png)
^ is the standard MC

![bild](https://user-images.githubusercontent.com/95881003/145466653-9502ae05-543a-4394-a076-c0ddee743f48.png)
^ is the Map MC i made

**Comment by nameouschangey** [comment] 2021-12-09 20:05
Perfect, thanks very much for uploading these!

I've been wondering until when some people said "it isn't working" if they meant "not launching at all"/"giving some error" or just "blank screen".

What's weird is it does appear to have started up correctly, as the screen in in 3x2 resolution. And then as if it's hung up somehow.

**Comment by nameouschangey** [comment] 2021-12-09 20:06
Out of curiosity, did you already have any Lua/Lua-Debug extensions installed before this?
Or was this the first time using VSCode with a Lua extension?

(Just wondering if it's similar to Mr.Lenyn's issue)

**Comment by nameouschangey** [comment] 2021-12-12 00:23
Latest build is now pushed live.

Please give it a try (you might be best to make a new project; just to be sure)
And then if you still get the issue, please send me screenshots and the _build/_debug_simulator_log.txt file

Many Thanks

**Comment by Shorkerrr** [comment] 2021-12-12 09:29
> Out of curiosity, did you already have any Lua/Lua-Debug extensions installed before this? Or was this the first time using VSCode with a Lua extension?
> 
> (Just wondering if it's similar to Mr.Lenyn's issue)

This would be the first time using VSCode. So no, i have not installed another Lua-Debugger before the Stormworks Extension. When i did install your plugin it did Install the Lua language and the Lua Debugger

**Comment by Shorkerrr** [comment] 2021-12-12 09:32
![bild](https://user-images.githubusercontent.com/95881003/145707247-29ec534a-c96c-4d46-b897-23b0bfefe590.png)
This is now happening after Reinstalling the plugin and resetting the MyMicrocontroller.lua file and the Simulator is still blank

**Comment by Shorkerrr** [comment] 2021-12-12 09:32
![bild](https://user-images.githubusercontent.com/95881003/145707297-06731839-0f3d-447f-b2df-066716d4d1b2.png)
Here

**Comment by Shorkerrr** [comment] 2021-12-12 09:33
![bild](https://user-images.githubusercontent.com/95881003/145707310-7b7e1ec9-d55f-4833-a8ef-0c200a99be60.png)
These are all the plugins ive got.

Also i dont know how to get the Log file for the simulator. Could you help me with that one?

**Comment by nameouschangey** [comment] 2021-12-12 11:48
Thanks for this!
And apologies that the latest patch hasn't fixed it for you yet.

The "undefined global onLBSimulatorInit" is fine - I'll get that warning removed, but it's causing no harm (we actually check if it's defined; and it's that line itself that causes the warning)

The log file should be generated when you run the simulator - it'll be in the folder `/_build/_debug_simulator_log.txt`
![image](https://user-images.githubusercontent.com/722981/145710875-2605ade4-e14e-40ed-8124-ffbfa562d970.png)

Hopefull we'll get to the bottom of this!

**Comment by Shorkerrr** [comment] 2021-12-12 11:53
![bild](https://user-images.githubusercontent.com/95881003/145711031-0817ef00-e250-477c-9ba7-093073a33b38.png)
for me it doesnt show the _debug_simulator_log.txt nor the _build.lua

is it in some other folder instead of the one where i added the plugin?

**Comment by nameouschangey** [comment] 2021-12-12 11:58
mm, that's strange
It should be in that /_build/ folder - it creates it any time the simulator runs
Might be part of the problem.

When you open VSCode, can you try right clicking and Run As Administrator (I doubt it'll work, but who knows)
Also can you let me know which operating system you're on, and which folder you've got the project saved in?


(The _build.lua will generate when you hit F7 - if that doesn't happen, also let me know; that'll be a new bug)

**Comment by Shorkerrr** [comment] 2021-12-12 12:06
>Also can you let me know which operating system you're on, and which folder you've got the project saved in?

Im running VSCode on Windows 11 pro. The folder is saved in the C drive. its not in program files or anything.

>(The _build.lua will generate when you hit F7 - if that doesn't happen, also let me know; that'll be a new bug)

i tried that and yes. it does create the _build.lua file but the simulator is still blank when i run it and it doesnt create a simulator log.

**Comment by Shorkerrr** [comment] 2021-12-12 12:07
![bild](https://user-images.githubusercontent.com/95881003/145711498-3476c928-af31-4f80-b025-7b65edfe4e69.png)
This is an issue aswell i think. its in the _build.lua file

**Comment by Shorkerrr** [comment] 2021-12-12 12:09
![bild](https://user-images.githubusercontent.com/95881003/145711576-bf26af7c-b36e-40f5-a335-cd10fdd2c3a8.png)
It also creates a new Folder when i click F7.

**Comment by nameouschangey** [comment] 2021-12-12 12:12
(Don't worry about that warning in the _build.lua file - it definitely works and exists in scope at that point. I'll get it cleaned up to remove the warning - but can ignore for now.

Also that new folder, the /out/ folder is correct - that's where it builds your files. You can copy from the /release/ folder to the game [it's minimized], or look at the /intermediate/ folder for the combined, but not minimized, version - where `require`s are resolved.)

Thanks for the info, that's really strange - it should begin logging before it's even started drawing the square at all.
When you start simulating, can you set some breakpoints to see how it progresses into your file?
Even if the visual simulator doesn't work - it should be running OK for a few frames in the lua.

**Comment by Shorkerrr** [comment] 2021-12-12 12:15
![bild](https://user-images.githubusercontent.com/95881003/145711727-fb654b43-3fda-4687-bf5b-dc2d3ec66a2b.png)
![bild](https://user-images.githubusercontent.com/95881003/145711742-28b6f5e1-9b11-447c-b139-62c5ddf3c005.png)

It doesnt give me any Breakpoints. even when activating ticking all the checks for the breakpoints. idk what could be going wrong

**Comment by nameouschangey** [comment] 2021-12-12 12:17
can you set some by clicking just left of the line-number, and see if the debugger trips them?

![image](https://user-images.githubusercontent.com/722981/145711811-1b3c454f-6ee1-453b-85f3-6f71b276fe70.png)

**Comment by Shorkerrr** [comment] 2021-12-12 12:20
![bild](https://user-images.githubusercontent.com/95881003/145711891-7e2b6c6d-31ac-4638-afbc-ea219dc1ccf6.png)
![bild](https://user-images.githubusercontent.com/95881003/145711897-66be175a-8ca1-4ed8-8d2e-f936999a8486.png)
^

**Comment by nameouschangey** [comment] 2021-12-12 12:22
Ok that's good - at least the debugger itself is working
If you let it run, does it trip e.g. within the onTick function, or is that never called?

**Comment by Shorkerrr** [comment] 2021-12-12 12:24
![bild](https://user-images.githubusercontent.com/95881003/145712021-19e1efc8-d011-445b-be1b-30a900f6a610.png)
im not exactly sure what i did but this just happened

**Comment by Shorkerrr** [comment] 2021-12-12 12:24
![bild](https://user-images.githubusercontent.com/95881003/145712059-46d141c6-558d-4ecc-b282-ba1552b890c3.png)
?

**Comment by nameouschangey** [comment] 2021-12-12 12:27
At least made a bit of progress there!
Can you try removing the spaces from your filepath - so it's something like C:/vscprojects/kopia3

(If this is the problem, I can fix that)

**Comment by Shorkerrr** [comment] 2021-12-12 12:29
>Can you try removing the spaces from your filepath - so it's something like C:/vscprojects/kopia3

wdym?

**Comment by nameouschangey** [comment] 2021-12-12 12:31
Sorry, I noticed in that red error it says:
![image](https://user-images.githubusercontent.com/722981/145712268-dd8b51db-5a28-4dba-bd8e-fc239977d11f.png)


Can you try making a project in a folder, where there are no spaces in the path.
For example:
C:/testFolder/mytest/
instead of
C:/test folder/my test/

It won't fix the simulator, but I just tested and that's the reason we didn't get a `/_build/_debug_simulator_log.txt` file

**Comment by Shorkerrr** [comment] 2021-12-12 12:35
Alright. Thats worked, its now giving me the _debug_simulator_log.txt file. although i cant upload it for some reason
![bild](https://user-images.githubusercontent.com/95881003/145712453-27ad041a-6368-44c6-bf0a-b6e8c042b969.png)

**Comment by Shorkerrr** [comment] 2021-12-12 12:36
[debuglog.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/7698728/debuglog.zip)
Ill just send it in a .zip file instead

**Comment by nameouschangey** [comment] 2021-12-12 12:40
Perfect, thank you so much!

I'm not sure what the cause of the error is; especially if you've reinstalled this multiple times.
But it shows the error big and clear - for some reason, when trying to draw anything, or do any commands - it can't parse the numbers it's being given from text into numbers.

I might need to get back to you to ask you to try some things, but we've got down to the problem at least! It's in the Simulator.exe and it's because it cannot parse the commands being sent.

(I think I might actually have an idea for a fix, I send you a debug version to try shortly)

Thanks so much!

**Comment by Shorkerrr** [comment] 2021-12-12 12:41
> Perfect, thank you so much!
> 
> I'm not sure what the cause of the error is; especially if you've reinstalled this multiple times. But it shows the error big and clear - for some reason, when trying to draw anything, or do any commands - it can't parse the numbers it's being given from text into numbers.
> 
> I might need to get back to you to ask you to try some things, but we've got down to the problem at least! It's in the Simulator.exe and it's because it cannot parse the commands being sent.
> 
> (I think I might actually have an idea for a fix, I send you a debug version to try shortly)
> 
> Thanks so much!

No problem man!

**Comment by nameouschangey** [comment] 2021-12-12 13:00
https://stackoverflow.com/questions/5592950/why-do-i-get-a-formatexception-when-converting-a-string-to-a-float

I think this might be the issue.

I'm guessing in Sweden [?sorry if I got that wrong] - the number format most people use isn't "123.345"?
I never realised the `float.Parse` and `int.Parse` functions in C# took account of cultures - I'd actually assumed they were Americanized/Anglicized and just expected it to be in English format.

So on your machine, it's expecting a number to be something like `100,1` but my code is sending `100.1`
If that sounds right, I'll have a fix by the end of today.
And if not, I've added better logging so we can track it down more easily.

**Comment by Shorkerrr** [comment] 2021-12-12 13:03
> https://stackoverflow.com/questions/5592950/why-do-i-get-a-formatexception-when-converting-a-string-to-a-float
> 
> I think this might be the issue.
> 
> I'm guessing in Sweden [?sorry if I got that wrong] - the number format most people use isn't "123.345"? I never realised the `float.Parse` and `int.Parse` functions in C# took account of cultures - I'd actually assumed they were Americanized/Anglicized and just expected it to be in English format.
> 
> So on your machine, it's expecting a number to be something like `100,1` but my code is sending `100.1` If that sounds right, I'll have a fix by the end of today. And if not, I've added better logging so we can track it down more easily.

Right. its slightly strange that it wants `100,1` instead of `100.1` even if the computer is in swedish as in my case. seems like an easy fix but idk i dont really do coding. Good luck!

**Comment by nameouschangey** [comment] 2021-12-12 14:04
That should be it fixed now, I never realised it used cultural number formats by default (there's an option to specify it, I always thought it defaulted to invariant; unless you specified. But it seems to default to the user's locale, unless you specify it's invariant)

Once you're on version 0.0.6 please give it a try and let me know.
Hopefully that's fixed it, but if not - it should have given us some better logging.

**Comment by nameouschangey** [comment] 2021-12-12 16:55
Same issue confirmed working by Dealman (also Swedish)

Thanks so much!
Let me know if you find any trouble, or want this re-opened.

**Closed by nameouschangey** 2021-12-12 16:55 UTC
Labels: bug, Fixed
