### ISSUE TITLE
unknown project specific bug

### ISSUE THREAD

**Issue by TheAdester** [nameouschangey/Stormworks_VSCodeExtension#99] opened 2022-06-14 06:59 UTC
[newproject.zip](https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/8897074/newproject.zip)

Hello,

this is a continuation from a troubleshooting attemp in the update threat on reddit from 13th June 2022.

[post from reddit:
  I tried this and got an error after pressing F7 in the file _build/_buildactions.lua:
  Exception has occurred: error loading module 'LifeBoatAPI' from file 'c:/Users/username/.vscode/extensions/nameouschangey.lifeboatapi-0.0.19/assets/luasocket/dll/socket/core.dll':
	  Die angegebene Prozedur wurde nicht gefunden.
  stack traceback:
	  _build/_buildactions.lua:8: in main chunk
	  [C]: in function 'require'
	  _build/_build.lua:2: in main chunk
	  [C]: in ?
  Any idea what i am doing wrong?
/post](https://www.reddit.com/r/Stormworks/comments/vay0mb/stormworks_lua_vscode_extension_major_update/ic6hmkw/)

A new project compiles/minifies fine, so i assume this has something to do with my code. The code itself works with the Pony IDE, but i didn't tested this version of the code in stormworks.

**Comment by nameouschangey** [comment] 2022-06-14 07:15
Thanks very much for this,

It looks like there's nothing you've done wrong - the settings.json file correctly has:

```
     "lifeboatapi.stormworks.libs.gitLibraries": [
        {
            "name": "LifeBoatAPI",
            "gitUrl": "https://github.com/nameouschangey/Stormworks_LifeBoatAPI_MC.git"
        }
```
But the /_build/libs/ folder is empty, so it didn't pull that library successfully (on your PC).
On mine, as soon as I opened the project - it pulled that library from git.


In your New Project, I'm guessing the _build/libs/ folder is still empty (it just "works" because I removed any references to that LifeBoatAPI library. But you'll be unable to use libraries if it's broken).
If so, can you try the following:
- right-click, Add Library From URL:  https://gist.github.com/02d48f4f30028eca88dc28e26b50d8dc.git  (this is a gist to your own file, feel free to look at it in a browser first)
- right-click, Update Libraries

If you get any visible error messages, please let me know what those are etc.

Otherwise, if you get nothing, can you try right-click: Share Link - which will ask you to log into your github account. After doing that (again share errors), can you try the above Add Library From URL again.

Many Thanks, apologies the libraries function isn't working for you.
It's not something you've done, just need to figure out what the bug is.

**Comment by nameouschangey** [comment] 2022-06-25 12:21
Did you recieve any errors/different behaviour from attempting the above?

I'm afraid as much as this is a bug, I've just not got any way to reproduce it currently.

**Comment by nameouschangey** [comment] 2022-07-01 23:35
Can't proceed without more info, closing for now.

**Closed by nameouschangey** 2022-07-01 23:35 UTC
Labels: bug, Rejected, Awaiting More Info
