### ISSUE TITLE
Build issue: property.getBool should be input.getBool

### ISSUE THREAD

**Issue by PirateJake2000** [nameouschangey/STORMWORKS_VSCodeExtension#67] opened 2022-02-12 19:26 UTC
once code has been "built" with F7 im getting the error "Attempt to call a nil value bx" I can see the issue being in this code "section":
cd=input
cc=output
**cb=property**
ca=screen
bZ=ca.drawTextBox
bY=ca.drawText
**bX=cb.getBool**
bW=cb.getNumber
bV=ca.setColor
bU=ca.drawTriangleF
bT=ca.drawCircleF

bX is cb.getBool but cb is property so its trying property.getBool? the real code is input.getBool I am not to sure why this is happening but here is some info on my script that might make it easier to reproduce:
Default length=4848
im using functions that are not in that script
all inputs are dealt with in the main script

 if you need more info and I dont respond my discord is PirateJake2000#5585

**Comment by PirateJake2000** [comment] 2022-02-12 19:30
only just seeing this now but its defining getBool twice?
bM=cd.getBool
bX=cb.getBool

I am not using any property Booleans (I don't even know if they exist so it has no reason to try and do property.getBool)

**Comment by PirateJake2000** [comment] 2022-02-12 21:55
changing some code fixed the issue but im not to sure why this happened to start with

**Comment by nameouschangey** [comment] 2022-02-12 22:42
Do you still have the original, broken, version (or able to recreate it)?

If so, please upload it, and also the fixed version.
I'm happy to look into whether it's an extension issue.

**Comment by nameouschangey** [comment] 2022-02-13 00:39
Thanks, might take some time - but I'll reply here once I've got an idea what's causing it and then can estimate a fix.

**Comment by nameouschangey** [comment] 2022-02-13 00:47
Found it, the issue is nothing to do with property.getBool or input.getBool
The value that's nil is "bx" not "bX"
And the reason it's nil is because you're calling "print" - which doesn't exist in Stormworks, and you've not defined it anywhere.

What I'd recommend, to save you needing a separate debug & in-game version, is to replace "print" with "debug.log" which I've setup to be print in the simulator, and in-game it will still work (sends to a debug output stream).

Closing this as it's just an unfortunate mistake.

**Closed by nameouschangey** 2022-02-13 00:47 UTC
Labels: Awaiting More Info

**Comment by PirateJake2000** [comment] 2022-02-13 14:18
oh god im stupid lmfao

**Comment by nameouschangey** [comment] 2022-02-13 16:21
No worries :)
