### ISSUE TITLE
Make Minimizer Options Accessible

### ISSUE THREAD

**Issue by Dealman** [nameouschangey/STORMWORKS_VSCodeExtension#19] opened 2021-12-15 20:37 UTC
Hey, been using this a bit more recently as I'm working on my own ECU for modular engines.

I've never developed extensions for VS Code so I'm not quite sure how modifiable it is, but I would imagine quite a bit. So I would like to propose a feature request to display the overall character count of the current script.

I think in the bottom right of the VS Code status bar would be an excellent position;
![image](https://user-images.githubusercontent.com/7038067/146261251-06e2775f-0a93-49f1-ad97-fa190f611182.png)

Pretty minor thing, but could help in keeping track of when you need to start refactoring stuff a bit. 😉 

**Edit:**

Derp, after writing this I figured there's most likely already an extension that does this so you don't have to make your own, and [yes there is](https://marketplace.visualstudio.com/items?itemName=j4ng5y.charactercount)...

Still, might be an easy implementation that some people may find useful so I'll leave this open so you can make a decision :shrug:

**Comment by nameouschangey** [comment] 2021-12-15 20:52
I could look at whether there's a better way to display the character count for the minimized files (the ones in /out/release/ after you hit F7). Right now they display the minimized count in the comment at the top (although this is removed if the file gets close to the 4K limit - so that the comment doesn't tip it over)

For the main files though, you really shouldn't need to be manually minimizing - there's only a couple of tricks that will get you a benefit (such as skipping the local keyword and putting those variables as parameters => minimizes slightly better), or reducing the number of if-statements using and/or syntax where possible.
But a lot of the "tricks" people use that they think work, like setting `s = screen` and using 1-letter variable names, at best do nothing useful except damage your code readability, and at worst actually decrease the ability of the minimizer to do its work effectively.
Hitting F7 should always be the go-to action.

For seeing the character counts in general though; I tend to just hit CTRL+A and then it tells you e.g. "2000 characters selected".

Let me know what you think would be helpful, otherwise I can close it :)

Thanks!

**Comment by Dealman** [comment] 2021-12-15 21:16
That's a fair point, personally I haven't made use of the minimize yet - if I release stuff I prefer to keep things readable. Thought the stuff I do release I usually post as a gist as well - so could always upload the minimized version and just link to a readable gist instead if need be.

Considering there's already an extension that does exactly what I proposed this is kind of a redundant feature I suppose.

**Comment by nameouschangey** [comment] 2021-12-15 21:46
Ah gotcha, hadn't considered people wanting to do that.

I'll see if I can expose more of the minimizer config - you can turn different minifications on/off (it's just not readily accessible in the Extension).
So might let you tailor a build process that works for you. 

So e.g.:
- remove comments
- keep variable names as-is
- minify SW globals (e.g. screen, input, output)
- keep whitespace readable

I think for things that specific character-count extension - it probably is better to just install it separately. And then the SW extension avoids bloating/enforcing too much on people's VSCode.

**Comment by Dealman** [comment] 2021-12-15 22:21
Personally I haven't quite made anything that's gotten to the character limit just yet - other than a little pong prototype I made for fun, but is not something I intend to release either way...

I'm probably the only one that creates a gist, it was more so if someone finds it and wanna try the logic real fast without having to subscribe - they can just joink the code from a gist.

I'm the kind of guy that strongly believe in readable code, so for me personally - not a huge fan of minimizers. But I do certainly see that it would be immensely useful for bigger projects.

**Comment by nameouschangey** [comment] 2021-12-15 22:31
Mm I get what you mean, I can see how it'd be helpful for somebody to be able to open the MC and read it - without having to goto your git, download VSCode and setup properly.

The workflow this was designed for was; edit your code in a readable, well organised format in VSCode - then minimize and send the "compiled" version into the game. So I'll have a think about what can be done to accomodate a "put the readable code in game" workflow (likely will be via minimizer options)

I 100% agree about readable code though, which was the reason for writing all of this - it was to encourage people not to shorten things into oblivion by hand - but store a *real* copy of the code outside the game, and do all editing in the readable, well organised code using multiple files/libraries.

The big thing you'll miss out on if you don't use the build chain at all though, is not being able to split code into reusable libraries or share code between multiple projects. So I think it'd, be worth finding something that lets you have both.

**Comment by nameouschangey** [comment] 2021-12-15 22:57
As the original request is solved by another extension, and this has all the info I need for a request I'd like to solve - renamed this.
Hope that's OK for you.

**Comment by Dealman** [comment] 2021-12-15 23:39
Perfectly fine with me! 👍

**Comment by nameouschangey** [comment] 2021-12-21 02:58
Fixed.
Settings will be available in 0.0.8

**Closed by nameouschangey** 2021-12-21 02:58 UTC
Labels: feature, Fixed
