### ISSUE TITLE
Simulation - Not Rendering as Expected (or at all)

### ISSUE THREAD

**Issue by Dealman** [nameouschangey/STORMWORKS_VSCodeExtension#8] opened 2021-12-07 18:01 UTC
Not sure how we're meant to work with the simulator, I tried yoinking some code from a simple battery level indicator I made the other day - basically it displays a gradient from top to bottom. It works as expected when simulating it using [Pony IDE](https://lua.flaffipony.rocks).

Example code:
```lua
local batteryLevel = 1.0

function onTick()
    batteryLevel = input.getNumber(1)
end

function onDraw()
    w, h = screen.getWidth(), screen.getHeight()
	
    for y=0, h do
        color = getGradientColor({0,255,0}, {255,0,0}, y/32)
        alpha = ((batteryLevel >= (1.0-(1/32*y))) and 255 or 0)
        screen.setColor(color[1], color[2], color[3], alpha)
        screen.drawLine(0,y,w,y)
    end
end
	
function getGradientColor(color1, color2, level)
    level = level * 100
   
    rDiff = -1*(color1[1] - color2[1])
    rPixel = rDiff / 100
    gDiff = -1*(color1[2] - color2[2])
    gPixel = gDiff / 100
    bDiff = -1*(color1[3] - color2[3])
    bPixel = bDiff / 100

    newRed = color1[1] + level * rPixel
    newGreen = color1[2] + level * gPixel
    newBlue = color1[3] + level * bPixel

    color = {newRed, newGreen, newBlue, ((level / 100) * 255)}

    return color
end
```

Trying to simulate this in VSCode results in a black monitor. I believe the issue is due to this line;
```lua
screen.setColor(color[1], color[2], color[3], alpha)
```

Am guessing the simulation can't really work with tables and need hardcoded values?

**Comment by nameouschangey** [comment] 2021-12-07 18:58
Thanks for raising this.
The code you've posted absolutely should work in the simulator, it's likely I've messed something up with the alpha channel.

Really appreciate you reporting this though, will get on it.

**Comment by Dealman** [comment] 2021-12-07 19:01
> Thanks for raising this. The code you've posted absolutely should work in the simulator, it's likely I've messed something up with the alpha channel.
> 
> Really appreciate you reporting this though, will get on it.

Heh, it's the very least I could do for such a powerful extension. 😄

**Comment by nameouschangey** [comment] 2021-12-08 23:55
I'm afraid I couldn't reproduce this.
The output I'm getting:
![image](https://user-images.githubusercontent.com/722981/145309440-d655519e-b337-4088-b906-7163b6f2c261.png)

Can you package the entire project folder you've got - and also take a screenshot?
Also, can you take a screenshot of your VSCode with the project open (there's 3 modes VSCode can open the project into, and I want to check which one it is) - make sure the "file explorer" part is open, it's the folder structure I need to see :)

Many thanks, and apologies I haven't managed to repro it

**Comment by nameouschangey** [comment] 2021-12-12 00:22
Can you try the latest update, pushed just now - and let me know if this has resolved for you.

I'd suggest making a new project just to be sure all the settings are correct. And if it still doesn't work, please copy the _build/_debug_simulator_log.txt so I can see what might have gone wrong, as well as screenshots of the issue.

Many Thanks.

**Comment by Dealman** [comment] 2021-12-12 12:50
Oh goodness, GitHub didn't notify me that had you replied - sorry about that.

[Test.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/7698744/Test.zip)
[_debug_simulator_log.txt](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/7698748/_debug_simulator_log.txt)

![image](https://user-images.githubusercontent.com/7038067/145712925-5536f5bf-ed5b-4748-93cc-ac7bd2e66444.png)

![image](https://user-images.githubusercontent.com/7038067/145712941-f26dc456-7001-436a-93c8-daca7e9a5793.png)

**Comment by nameouschangey** [comment] 2021-12-12 13:03
Perfect thanks so much!

Looking at that _debug_log_text file, it looks like this is a cultural issue with the `int.Parse` and `float.Parse` in C# (the same issue another user has just been reporting)

I think we can get a fix for this shortly.
Just for reference, which country are you in?

Thanks so much!

**Comment by Dealman** [comment] 2021-12-12 13:14
![image](https://user-images.githubusercontent.com/7038067/145713789-4c4b24c8-26f9-4df7-b552-c5ea218911da.png) 
😄

**Comment by nameouschangey** [comment] 2021-12-12 14:05
xD Sorry! Turns out there was a bug that literally was excluding everybody in Sweden (Number format issues)

It's fixed now, and version 0.0.6 is live - it should fix it, but if not, let me know.
You might need to wait a few minutes/re-launch VSCode for it to update to the latest version.

Please let me know if it works!

**Comment by Dealman** [comment] 2021-12-12 16:29
Sorry for the delay, it works as expected now! Great work, look forward to using this now 😃

**Comment by nameouschangey** [comment] 2021-12-12 16:52
Amazing, thanks for letting me know!

Glad it's working for you now - should be for Shorkerrr as well!
Hope you enjoy, and just give a shout if anything else goes wrong :)

**Closed** 2021-12-12 16:52 UTC
Labels: bug, Fixed
