### ISSUE TITLE
Minimizer setting all build options to False, despite VSCode settings

### ISSUE THREAD

**Issue by samohtGTO** [nameouschangey/STORMWORKS_VSCodeExtension#88] opened 2022-06-02 14:57 UTC
how to change the params the are automatly set to false every time i build

**Comment by samohtGTO** [comment] 2022-06-02 14:57
<img width="777" alt="image" src="https://user-images.githubusercontent.com/71775252/171658828-3ca6c913-3261-472e-a104-4fb9617bc7b5.png">

**Comment by nameouschangey** [comment] 2022-06-02 15:08
the _build.lua file is generated every time you build.
you can change these in the _build_actions.lua file - although I'd recommend just setting the various settings in the Extension Settings (CTRL+COMMA) instead of via code.

**Comment by samohtGTO** [comment] 2022-06-02 15:47
it doesnt change them

**Comment by nameouschangey** [comment] 2022-06-02 16:31
OK, please set the workspace/folder settings; and then zip and send me the project.
I'll have a look and see.

**Comment by samohtGTO** [comment] 2022-06-02 17:16
[bugbuild.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/8826088/bugbuild.zip)

**Comment by nameouschangey** [comment] 2022-06-02 18:31
![Untitled](https://user-images.githubusercontent.com/722981/171701051-c665d845-fd2d-4e9e-83ab-8af35affdc28.png)

Minifier settings are working as expected.
It may be that you didn't realise you've set all these values on a "per-folder" level (VSCode stores that into settings.json), and when you went into the settings menu; you changed them as User settings.
For reference, VSCode will take values from folder settings, then workspace settings if not set in folder, and finally user settings if not either of the previous ones. You may want to go into the folder settings and click "Reset" on each of those.

That's just how VSCode works though, it's not under my control.
Everything appears to be working as expected though - so closing.

**Comment by samohtGTO** [comment] 2022-06-03 19:22
question when does it define the params so that maybe make it easier to find for me were to look

**Comment by nameouschangey** [comment] 2022-06-03 22:06
See above, hit CTRL+COMMA and you can set your minifier settings in the VSCode settings.

**Comment by samohtGTO** [comment] 2022-06-05 09:22
i know but is it maybe windows 11 because i treid my best to find a prefolder
and i know about the vscode settinigs sadly

**Comment by nameouschangey** [comment] 2022-06-05 10:24
"is it maybe this"
"could it be that"

1) "treid my best to find a prefolder" - what are you even on about?

2) No, unless you can show some reproduction steps, give some detailed information for me to work on - this issue is closed.
I've checked out your project, as far as I can tell - it works.
You have every default minimizer setting turned ON in the settings.json file; it's doing what it's meant to do. If you want to change those settings, use CTRL+COMMA. Again, tested on your project, and it works exactly as expected.

Right now, my gut feeling is you're trying to do something this wasn't designed for you to do - and you're not competent enough to figure it out by yourself. Either use the settings as intended, or give me a detailed report of what's wrong, or leave this closed.

If you don't have specific, written out reproduction steps in your next reply; I'm going to have to block you. This is a complete waste of my weekend.

**Comment by samohtGTO** [comment] 2022-06-05 10:35
im sry but the minimizer keeps set to false everthing i follew you step by step so i guess it doesnt work on my pc so this is my last messagein this issue

**Comment by nameouschangey** [comment] 2022-06-05 10:58
OK, apologies for getting frustrated with this issue.

Let me mark this as a bug - I'm not sure I'll ever be able to reproduce it. If I do, I'll fix it.
I'll clear these comments, as I'm in the wrong - apologies.

**Comment by samohtGTO** [comment] 2022-06-05 11:07
i got a idea tommorow i do it but it now enough for today

**Comment by samohtGTO** [comment] 2022-06-06 16:46
i tried to re define it but it wont is de minimizer settings a constant

**Comment by samohtGTO** [comment] 2022-06-08 13:33
<img width="726" alt="image" src="https://user-images.githubusercontent.com/71775252/172629555-dd0d90f3-c59e-411a-9caf-8900b637dde8.png">

**Comment by nameouschangey** [comment] 2022-06-10 08:46
Please stop closing issues that aren't resolved.

Thanks to BobBob13, who also had this issue - and explained what was actually happening, I've got a fix on the way.

**Comment by nameouschangey** [comment] 2022-06-10 09:02
Fixed applied, will release today

**Closed by nameouschangey** 2022-06-10 09:02 UTC
Labels: bug, Fixed

**Comment by samohtGTO** [comment] 2022-06-10 10:51
question what was the problem

**Comment by nameouschangey** [comment] 2022-06-10 11:41
VSCode is running some people's commandline via CMD instead of Powershell. If there's newlines in the command (there are), those separate it into multiple commands, which means you're losing 90% of the command you actually needed. Everything after that will break, such as finding requires, minimizer params etc.

It should be possible to just change your terminal, but it was preferable just to fix it so it works for everything instead.

**Comment by samohtGTO** [comment] 2022-06-10 13:08
oh i remeber changing to that
